[package]
name = "frame-test"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "28.0"
winit = { version = "0.30", features = ["rwh_06"] }
pollster = "0.4"
clap = { version = "4.5", features = ["derive"] }
bytemuck = { version = "1.15", features = ["derive"] }
